CREATE TABLE PROYECTO (
ID BIGSERIAL PRIMARY KEY,
NOMBRE VARCHAR(255),
ESTADO VARCHAR(255) unique,
FECHA_INICIO DATE,
FECHA_FIN DATE,
ID_LIDER INTEGER NOT NULL,
FECHA_ALTA DATE,
FECHA_MODIFICACION DATE,
USUARIO_ALTA BIGINT,
USUARIO_MODIFICACION int);
	

CREATE TABLE PARAMETRO (
ID BIGSERIAL PRIMARY KEY,
DOMINIO VARCHAR (50),
VALOR VARCHAR (50) ,
ORDEN VARCHAR(50),
DESCRIPCION VARCHAR(1000)
);

CREATE TABLE USUARIO (
ID BIGSERIAL PRIMARY KEY,
NOMBRE_COMPLETO VARCHAR(255),
ID_ROL INTEGER ,
CONTRASEÑA VARCHAR(255),
USERNAME VARCHAR(255),
EMAIL VARCHAR(255)
);

CREATE TABLE FASE (
ID BIGSERIAL PRIMARY KEY,
ID_PROYECTO INTEGER UNIQUE NOT NULL,
ESTADO VARCHAR(25) unique,
FECHA_ALTA DATE,
USUARIO_MODIFICACION int UNIQUE,
USUARIO_ALTA BIGINT UNIQUE,
FECHA_MODIFICACION DATE
);


CREATE TABLE USUARIO_ROL_PROYECTO (
ID_PROYECTO INTEGER,
ID_ROL INTEGER,
ID_USUARIO INTEGER,
PRIMARY KEY (ID_PROYECTO,ID_ROL,ID_USUARIO)
);	
	

CREATE TABLE ROL (
ID BIGSERIAL PRIMARY KEY,
NOMBRE VARCHAR (255),
DESCRIPCION VARCHAR (255)
);

CREATE TABLE PERMISO_ROL (
ID_ROL INTEGER,
ID_PERMISO INTEGER,
PRIMARY KEY (ID_ROL,ID_PERMISO)
);


CREATE TABLE PERMISO (
ID BIGSERIAL PRIMARY KEY,
NOMBRE VARCHAR(100),
DESCRIPCION VARCHAR (1000)
);


CREATE TABLE LINEA_BASE (
ID BIGSERIAL PRIMARY KEY,
ID_FASE INTEGER unique,
ESTADO VARCHAR(40),
FECHA_ALTA DATE,
FECHA_MODIFICACION DATE,
USUARIO_MODIFICACION int UNIQUE,
USUARIO_ALTA BIGINT UNIQUE
);


CREATE TABLE ITEM (
ID BIGSERIAL PRIMARY KEY,
ID_ITEM_PADRE INTEGER UNIQUE,
ID_FASE INTEGER UNIQUE,
ESTADO VARCHAR (25) UNIQUE,
ID_LINEA_BASE INTEGER UNIQUE,
FECHA_ALTA DATE,
FECHA_MODIFICACION DATE,
USUARIO_MODIFICACION int UNIQUE,
USUARIO_ALTA BIGINT UNIQUE,
OBSERVACION VARCHAR (70),
DESCRIPCION VARCHAR (50),
PRIORIDAD VARCHAR (20)
);


ALTER TABLE PROYECTO ADD CONSTRAINT USUARIO_ALTA_FKEY FOREIGN KEY (USUARIO_ALTA)
REFERENCES FASE (USUARIO_ALTA) MATCH SIMPLE
	ON UPDATE NO ACTION ON DELETE NO ACTION;

	
ALTER TABLE PROYECTO ADD CONSTRAINT USUARIO_MODIFICACION_FKEY FOREIGN KEY (USUARIO_MODIFICACION)
REFERENCES FASE (USUARIO_MODIFICACION) MATCH SIMPLE
	ON UPDATE NO ACTION ON DELETE NO ACTION;


ALTER TABLE FASE ADD CONSTRAINT USUARIO_ALTA_FKEY2 FOREIGN KEY (USUARIO_ALTA)
REFERENCES LINEA_BASE (USUARIO_ALTA) MATCH SIMPLE
	ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE FASE ADD CONSTRAINT ID_PROYECTO_FKEY FOREIGN KEY (USUARIO_ALTA)
REFERENCES PROYECTO (ID) MATCH SIMPLE
	ON UPDATE NO ACTION ON DELETE NO ACTION;
	
ALTER TABLE FASE ADD CONSTRAINT USUARIO_MODIFICACION_FKEY2 FOREIGN KEY (USUARIO_MODIFICACION)
REFERENCES LINEA_BASE (USUARIO_MODIFICACION) MATCH SIMPLE
	ON UPDATE NO ACTION ON DELETE NO ACTION;


ALTER TABLE USUARIO_ROL_PROYECTO ADD CONSTRAINT USUARIO_ROL_PROYECTO_FKEY FOREIGN KEY (ID_PROYECTO)
REFERENCES PROYECTO (ID) MATCH SIMPLE
	ON UPDATE NO ACTION ON DELETE NO ACTION;
	
	
ALTER TABLE USUARIO_ROL_PROYECTO ADD CONSTRAINT ID_ROL_FKEY FOREIGN KEY (ID_ROL)
REFERENCES ROL (ID) MATCH SIMPLE
	ON UPDATE NO ACTION ON DELETE NO ACTION;
	

ALTER TABLE USUARIO_ROL_PROYECTO ADD CONSTRAINT ID_USUARIO_2_FKEY FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO (ID) MATCH SIMPLE
	ON UPDATE NO ACTION ON DELETE NO ACTION;


ALTER TABLE PERMISO_ROL ADD CONSTRAINT ID_ROL_2_FKEY FOREIGN KEY (ID_ROL)
REFERENCES ROL (ID) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION;


ALTER TABLE PERMISO_ROL ADD CONSTRAINT ID_PERMISO_2_FKEY FOREIGN KEY (ID_PERMISO)
REFERENCES PERMISO (ID) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION;


ALTER TABLE LINEA_BASE ADD CONSTRAINT ID_FASE_2_FKEY FOREIGN KEY (ID_FASE)
REFERENCES FASE (ID) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION;


ALTER TABLE LINEA_BASE ADD CONSTRAINT ID_USUARIO_ALTA_2_FKEY FOREIGN KEY (USUARIO_ALTA)
REFERENCES ITEM (USUARIO_ALTA) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION;


ALTER TABLE LINEA_BASE ADD CONSTRAINT USUARIO_MODIFICACION_2_FKEY FOREIGN KEY (USUARIO_MODIFICACION)
REFERENCES ITEM (USUARIO_MODIFICACION) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION;


ALTER TABLE ITEM ADD CONSTRAINT ITEM_PADRE_FKEY FOREIGN KEY (ID_ITEM_PADRE)
REFERENCES ITEM (USUARIO_MODIFICACION) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION;


ALTER TABLE ITEM ADD CONSTRAINT LINEA_BASE_3_FKEY FOREIGN KEY (ID_LINEA_BASE)
REFERENCES LINEA_BASE (ID) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION;


ALTER TABLE ITEM ADD CONSTRAINT USUARIO_MODIFICACION_3_FKEY_FKEY FOREIGN KEY (USUARIO_MODIFICACION)
REFERENCES LINEA_BASE (USUARIO_MODIFICACION) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION;


ALTER TABLE ITEM ADD CONSTRAINT USUARIO_ALTA_3_FKEY FOREIGN KEY (USUARIO_ALTA)
REFERENCES LINEA_BASE (USUARIO_ALTA) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION;