CREATE TABLE PROYECTO (
ID INTEGER PRIMARY KEY,
NOMBRE VARCHAR(255),
ESTADO VARCHAR(255),
FECHA_INICIO DATE,
FECHA_FIN DATE,
ID_LIDER INTEGER NOT NULL,
FECHA_ALTA DATE,
FECHA_MODIFICACION DATE,
USUARIO_ALTA VARCHAR(70),
USUARIO_MODIFICACION VARCHAR(70));

ALTER TABLE PROYECTO ADD CONSTRAINT USUARIO_ALTA_FKEY FOREIGN KEY (USUARIO_ALTA)
REFERENCES FASE (USUARIO_ALTA) MATCH SIMPLE
	ON UPDATE NO ACTION ON DELETE NO ACTION;
	
ALTER TABLE PROYECTO ADD CONSTRAINT USUARIO_MODIFICACION_FKEY FOREIGN KEY (USUARIO_MODIFICACION)
REFERENCES FASE (USUARIO_MODIFICACION) MATCH SIMPLE
	ON UPDATE NO ACTION ON DELETE NO ACTION;
	

CREATE TABLE PARAMETRO (
ID INTEGER PRIMARY KEY,
DOMINIO VARCHAR (50),
VALOR VARCHAR (50) ,
ORDEN VARCHAR(50),
DESCRIPCION VARCHAR(50)
);

CREATE TABLE FASE (
ID INTEGER PRIMARY KEY,
ID_PROYECTO INTEGER NOT NULL,
ESTADO VARCHAR(25),
FECHA_ALTA DATE,
USUARIO_MODIFICACION VARCHAR(70),
USUARIO_ALTA VARCHAR(70),
FECHA_MODIFICACION DATE,
UNIQUE(USUARIO_ALTA),
UNIQUE(ID_PROYECTO),
UNIQUE(USUARIO_MODIFICACION));

ALTER TABLE FASE ADD CONSTRAINT USUARIO_ALTA_FKEY2 FOREIGN KEY (USUARIO_ALTA)
REFERENCES LINEA_BASE (USUARIO_ALTA) MATCH SIMPLE
	ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE FASE ADD CONSTRAINT ID_PROYECTO_FKEY FOREIGN KEY (USUARIO_ALTA)
REFERENCES PROYECTO (ID) MATCH SIMPLE
	ON UPDATE NO ACTION ON DELETE NO ACTION;
	
ALTER TABLE FASE ADD CONSTRAINT USUARIO_MODIFICACION_FKEY2 FOREIGN KEY (USUARIO_MODIFICACION)
REFERENCES LINEA_BASE (USUARIO_MODIFICACION) MATCH SIMPLE
	ON UPDATE NO ACTION ON DELETE NO ACTION;


CREATE TABLE USUARIO_ROL_PROYECTO (
ID_PROYECTO INTEGER,
ID_ROL INTEGER,
ID_USUARIO INTEGER,
PRIMARY KEY (ID_PROYECTO,ID_ROL,ID_USUARIO)
);	

ALTER TABLE USUARIO_ROL_PROYECTO ADD CONSTRAINT USUARIO_ROL_PROYECTO_FKEY FOREIGN KEY (ID_PROYECTO)
REFERENCES PROYECTO (ID) MATCH SIMPLE
	ON UPDATE NO ACTION ON DELETE NO ACTION;
	

ALTER TABLE USUARIO_ROL_PROYECTO ADD CONSTRAINT ID_ROL_FKEY FOREIGN KEY (ID_ROL)
REFERENCES ROL (ID) MATCH SIMPLE
	ON UPDATE NO ACTION ON DELETE NO ACTION;
	

ALTER TABLE USUARIO_ROL_PROYECTO ADD CONSTRAINT ID_USUARIO_2_FKEY FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO (ID) MATCH SIMPLE
	ON UPDATE NO ACTION ON DELETE NO ACTION;	

CREATE TABLE ROL (
ID INTEGER PRIMARY KEY,
NOMBRE VARCHAR (255),
DESCRIPCION VARCHAR (255)
);

CREATE TABLE PERMISO_ROL (
ID_ROL INTEGER,
ID_PERMISO INTEGER,
PRIMARY KEY (ID_ROL,ID_PERMISO)
);

ALTER TABLE PERMISO_ROL ADD CONSTRAINT ID_ROL_2_FKEY FOREIGN KEY (ID_ROL)
REFERENCES ROL (ID) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE PERMISO_ROL ADD CONSTRAINT ID_PERMISO_2_FKEY FOREIGN KEY (ID_PERMISO)
REFERENCES PERMISO (ID) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION;

CREATE TABLE PERMISO (
ID INTEGER PRIMARY KEY,
NOMBRE VARCHAR(70),
DESCRIPCION VARCHAR (100)
);

CREATE TABLE LINEA_BASE (
ID INTEGER PRIMARY KEY,
ID_FASE INTEGER,
ESTADO VARCHAR(40),
FECHA_ALTA DATE,
FECHA_MODIFICACION DATE,
USUARIO_MODIFICACION VARCHAR (70),
USUARIO_ALTA VARCHAR (70),
UNIQUE (USUARIO_ALTA)
UNIQUE (USUARIO_MODIFICACION)
);

ALTER TABLE LINEA_BASE ADD CONSTRAINT ID_FASE_2_FKEY FOREIGN KEY (ID_FASE)
REFERENCES FASE (ID) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE LINEA_BASE ADD CONSTRAINT ID_USUARIO_ALTA_2_FKEY FOREIGN KEY (ID_USUARIO_ALTA)
REFERENCES ITEM (USUARIO_ALTA) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE LINEA_BASE ADD CONSTRAINT USUARIO_MODIFICACION_2_FKEY FOREIGN KEY (USUARIO_MODIFICACION)
REFERENCES ITEM (USUARIO_MODIFICACION) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION;

create table item (
id integer,
id_item_padre integer,
estado varchar (25),
id_linea_base integer,
fecha_alta date,
fecha_modificacion date,
usuario_modificacion varchar (25),
usuario_alta varchar (25),
observacion varchar (70),
descripcion varchar (50),
prioridad varchar (20)
);


